### ISSUE TITLE
Drawer "open" cannot reopen after close on first instance.

### ISSUE THREAD

**Issue by ONLYstcm** [StratoDem/sd-material-ui#116]
I have a drawer component that is not docked. It can open fine on first instance when you set 'open' to True. If ESC is pressed or a mouse is clicked elsewhere then the drawer will close however it will not open again even if 'open' is set to True. 

It seems to be very similar to the problem described in issue #85.

**Comment by coralvanda** [comment]
Thanks for pointing that out. Should be very easy if it's the same problem. I'll take a look.

**Comment by mjclawar** [comment]
Closed by #117, released in [v3.0.2](https://github.com/StratoDem/sd-material-ui/releases/tag/v3.0.2)
