### ISSUE TITLE
Is it possible to set drawer width?

### ISSUE THREAD

**Issue by vetertann** [StratoDem/sd-material-ui#118]
Hi, currently drawer size seems to be fixed. Is there any possibility to change it?
Great job on the module, btw, thank you!!

**Comment by coralvanda** [comment]
It is possible. [Here](https://github.com/StratoDem/sd-material-ui/blob/master/src/components/Drawer/Drawer.react.js#L48-L51) is the section where that prop is explained. You can do something like this:

```python
sd_material_ui.Drawer(
    id='my-id',
    width='30%',
    **other_props
)
```

**Comment by vetertann** [comment]
@coralvanda Thank you!!
