### ISSUE TITLE
sd_material_ui was not found

### ISSUE THREAD

**Issue by CloudZazu** [StratoDem/sd-material-ui#119]
Got the following error as a browser console error: 
```
Failed to load resource: the server responded with a status of 404 ()
react-dom.production.min.js:117 Error: sd_material_ui was not found.
    at Object.resolve (registry.js:17)
    at q (TreeContainer.js:226)
    at G (TreeContainer.js:263)
    at TreeContainer.js:303
    at connect.js:110
    at i.updateMergedPropsIfNeeded (connect.js:224)
    at i.render (connect.js:348)
    at ce (react-dom.production.min.js:98)
    at qg (react-dom.production.min.js:97)
    at hi (react-dom.production.min.js:104)
Bg @ react-dom.production.min.js:117
```

After debugging it, it seems like it was introduced at release version 3.0.1
Code was hosted on a Linux Centos (CentOS Linux release 7.3.1611 (Core)) on Flask production mode.
I do not see any error information on the server end.
No graphics are displayed on browser as a result of this error.

**Comment by coralvanda** [comment]
Can you provide a code sample that reliably reproduces this issue?

**Comment by CloudZazu** [comment]
I was able to reproduce it with the code snippet that was provided on the README. I've only changed a few lines to get it to run.
```import dash
import dash_html_components as html

import sd_material_ui


my_app = dash.Dash()

# A FlatButton on Paper
my_app.layout = sd_material_ui.Paper([
  html.Div(children=[
    html.P(id='output', children=['n_clicks value: . n_clicks_previous value: '])
  ]),

  sd_material_ui.FlatButton(id='input', label='Click me', backgroundColor='orange'),
])


# Callback for FlatButton
@my_app.callback(
  dash.dependencies.Output('output', 'children'),
  [dash.dependencies.Input('input', 'n_clicks')],
  [dash.dependencies.State('input', 'n_clicks_previous')])
def display_clicks_flat(n_clicks_flat: int, n_clicks_flat_prev: int):
  if n_clicks_flat:
    return ['n_clicks value: {}. n_clicks_prev value: {}'.format(n_clicks_flat,
                                                                 n_clicks_flat_prev)]
  else:
    return ['n_clicks value: ']

if __name__ == '__main__':
  my_app.run_server(host='0.0.0.0', port=80)```

**Comment by coralvanda** [comment]
I tried running this just a moment ago, only changing to use `my_app.run_server(debug=True)`, and there were no errors, but removing the `debug=True` and reloading did generate this same error. Thanks for reporting this. We'll check it out.

**Comment by coralvanda** [comment]
Still not entirely sure where the problem is coming from, but here is a solution. Add this line to your app definition:

`app.scripts.config.serve_locally = True`

With that line in place, I can no longer reproduce this issue. Perhaps something about forcing Dash to work offline pulls in the package in a way that avoids whatever the problem is otherwise.

**Comment by CloudZazu** [comment]
Interesting that does sound like a fair assumption. Also read this on plotly forums so it does support your suspicion where that option does package it appropriately it seems.  https://community.plot.ly/t/serve-locally-option-with-additional-scripts-and-style-sheets/6974/24. That seemed to have resolved my issue on my end. Thanks!
