### ISSUE TITLE
Changing color of a Drawer component

### ISSUE THREAD

**Issue by eddy-ojb** [StratoDem/sd-material-ui#122]
Hi,

Great package. Thank you.

Changing the background color of the drawer component doesn't work when copying the syntax as laid out in usage.py. Am I missing something? I am stuck with just a white background.

**Comment by coralvanda** [comment]
Hi, thanks for mentioning that. I run into the same problem, so it's a bad example. You'll have to use CSS to set that background color. If you set the `containerClassName` prop, that will be the class name you can use in CSS to change the background color.

**Comment by oi-eddyoj** [comment]
Great, thanks for solving!
