### ISSUE TITLE
href in DropDownMenu 

### ISSUE THREAD

**Issue by oi-eddyoj** [StratoDem/sd-material-ui#146]
Can this contain an href element? I would like to add links to other pages in the dropdown

**Comment by coralvanda** [comment]
It cannot currently contain an href element, but I'll keep this issue open for when we have time to come back around to it.

**Comment by coralvanda** [comment]
Even after updating to v4.0.0, the dropdown is not capable of handling an href. This is based on the underlying MUI component, which also cannot accept an href. Closing issue.
