### ISSUE TITLE
Dialog cannot work with Dash 1.10.0

### ISSUE THREAD

**Issue by sandrayin** [StratoDem/sd-material-ui#332]
Initially designed a website with Dialog component with an old Dash version. After upgrading Dash, the Dialog component stops working with Dash 1.10.0. 

Tried reinstall Dash 1.9.0 with the rest of its libraries. The dialog box works as expected.

Observation on 1.10.0: Put anything inside the Dialog children with html.Div or html.Button or even material UI's button. The dialog stop working. Plain string still works.

**Comment by coralvanda** [comment]
Thank you for flagging this.

**Comment by coralvanda** [comment]
Closed by #420
