### ISSUE TITLE
Restructure src directory for each component to have own directory with documentation

### ISSUE THREAD

**Issue by mjclawar** [StratoDem/sd-material-ui#52]
### Description
New project structure should look like: 
```
- src/
    - index.js
    - Dropdown/
        - index.js
        - Dropdown.react.js
        - Dropdown.md
    - FlatButton/
        - index.js
        - FlatButton.react.js
        - FlatButton.md
    ...
```
Documentation for each component, with examples and images/gifs should go in `MyComponent.md` in the directory. Static assets can be placed in a separated `static` directory that is listed in a `.npmignore` file in the project base.

**Comment by coralvanda** [comment]
closed by 2acc57c52b1b846c575d4211abd54fc2ed5a38f9
