### ISSUE TITLE
Error module 'sd_material_ui' has no attribute 'IconButton'

### ISSUE THREAD

**Issue by juancece** [StratoDem/sd-material-ui#524]
## Tasks

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

**Comment by juancece** [comment]
running dash-ui advanced_ddemo.py, the sd-material-ui throws this error. I see that the __init__.py does not have IconButton

**Comment by coralvanda** [comment]
Yes, for v4.0.0 we combined all of the buttons into a single component, `Button`, which accepts a `variant` prop to create the different types of buttons that were previously available.
