### ISSUE TITLE
Rename components to remove "SD" prefix

### ISSUE THREAD

**Issue by mjclawar** [StratoDem/sd-material-ui#53]
### Description
Components should be renamed to drop the "SD" prefix, e.g., the `SDDropdown` should be renamed to just `Dropdown`. 

This will require importing the base `material-ui` components with aliases, like
```js
import MuiDropdown from 'material-ui/Dropdown'; // vs import Dropdown from 'material-ui/Dropdown';
...
class Dropdown extends React.Component {
    render() {
        return <Dropdown ... />
    ...
```

**Comment by coralvanda** [comment]
closed by 2acc57c52b1b846c575d4211abd54fc2ed5a38f9
