### ISSUE TITLE
import sd_material_ui leads to ModuleNotFoundError: No module named 'sd_material_ui.Picker'

### ISSUE THREAD

**Issue by JonThom** [StratoDem/sd-material-ui#566]
## Description
When importing sd_material_ui module, the following error occurs:

> Traceback (most recent call last):
>   File "/Users/rkm916/Sync/projects/2020-dashforcegraph/index.py", line 12, in <module>
>     import sd_material_ui
>   File "/Users/rkm916/.local/share/virtualenvs/2020-dashforcegraph-KG21hdZa/lib/python3.9/site-packages/sd_material_ui/__init__.py", line 10, in <module>
>     from ._imports_ import *
>   File "/Users/rkm916/.local/share/virtualenvs/2020-dashforcegraph-KG21hdZa/lib/python3.9/site-packages/sd_material_ui/_imports_.py", line 18, in <module>
>     from .Picker import Picker
> ModuleNotFoundError: No module named 'sd_material_ui.Picker'
> 

## To Reproduce

install the module via pipenv
`pipenv install sd-material-ui `

start the Dash server (script includes `import sd_material_ui`)
`pipenv run python index.py`

**Comment by coralvanda** [comment]
@JonThom thank you for making this issue. The v4.3.2 release should fix it.
