### ISSUE TITLE
Add n_clicks_previous to buttons to mimic new dash-html-components logic

### ISSUE THREAD

**Issue by mjclawar** [StratoDem/sd-material-ui#60]
### Discussion
As discussed in https://github.com/plotly/dash-html-components/pull/37, buttons are much more convenient when the user can determine which button was clicked in the case where multiple buttons are used for a callback.

Adding an `n_clicks_previous` prop to at least `RaisedButton` and `FlatButton` would clean up a lot of logic in downstream code.

**Comment by coralvanda** [comment]
Although there are two updates to props, the single click event fired off appears to hit the server only one time per button press. Watch the `POST` updates in the console in this gif as each button is clicked.

![button-test](https://user-images.githubusercontent.com/16080662/36736641-23269736-1ba7-11e8-9e74-6cffdda7b0ff.gif)
