### ISSUE TITLE
Validation of available material-ui components and how to implement

### ISSUE THREAD

**Issue by whisoer** [StratoDem/sd-material-ui#630]
## Description

Hi, as we talk recently in #623  the select component already was ported to sd-material-ui. So I would like to verify the existent components and check how can I use them.

I have the need to use these material-ui components:

- [ ] [Textfield](https://material-ui.com/components/text-fields/)
- [x] [Select](https://material-ui.com/components/selects/)
- [x] [Date Picker](https://material-ui.com/components/pickers/#date-time-pickers)
- [ ] [Slider](https://material-ui.com/components/slider/#slider)
- [ ] [Table](https://material-ui.com/components/tables/#table)
- [x] [Dialog](https://material-ui.com/components/dialogs/#dialog)
- [x] [Card](https://material-ui.com/components/cards/#card)

Could you please validate which ones are available and how to implementation would be like the below example? So I can use what is already accessible and validate my prioritization of which component to bring first.

example:
```python
sd_material_ui.Button(id='input', children='Click me')
```

**Comment by coralvanda** [comment]
Yes. Date picker is available as the picker component, dialog and card use the same names, and select is dropdown, as we said.

We have examples of the components being used in the [usage.py](https://github.com/StratoDem/sd-material-ui/blob/master/usage.py) file.
