### ISSUE TITLE
Question about the classes attribute

### ISSUE THREAD

**Issue by vikigenius** [StratoDem/sd-material-ui#695]
How do we actually use the `classes` parameter provided by the components.

Can you give an example of how it can be used. The Python generated docs say that it should be a dict, but I don't understand what the values to those dict are.

**Comment by coralvanda** [comment]
Sure thing, The keys are the parts of the component, which are usually included in the docs, and the values are the CSS classnames you want to use,

```python
classes = {
    'root': 'my-dark-class',
    'paper': 'my-bold-class',
}
```
