### ISSUE TITLE
Creating a similar library for Carbon Design theme

### ISSUE THREAD

**Issue by bedangSen** [StratoDem/sd-material-ui#728]
## Tasks

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

**Comment by coralvanda** [comment]
Hi, @bedangSen, and thanks!

It would be a pretty heavy lift to port over the Carbon Design components to Dash, mostly because of the time required. It's not something we plan to undertake, but that could be a good way to get yourself into making new Dash components.
