### ISSUE TITLE
Providing initial Picker value causes inconsistent timezone behavior

### ISSUE THREAD

**Issue by MCBoarder289** [StratoDem/sd-material-ui#729]
## Description

Thanks for providing this awesome library! Below is the issue I'm experiencing, and I tried to provide as much initial research/info as possible hoping that's helpful.

**Issue**

When passing an initial value to the Picker, it appears that it takes the server default timezone and displays a different date then what the value is (see initial state of gif below: value passed is "2020-01-01" but the displayed value in the Picker is "2019-12-31"). 

If you never type in the picker and just use the UI, the initial server timezone will be used and the value will be the next day (or end of day).

Once you begin typing, it will convert to the browsers timezone and remain that way until you refresh the page. 

However if you do *not* provide an initial value, it will always use the browser timezone and this mismatch never occurs.

The inconsistent behavior there makes it difficult to rely on the value we take in a callback or filtering when providing it an initial value. Initially we'll want to subtract a day, but when typing and from then on we need to take the date as is. 

**Some Research**

- I provided a simple app below that replicates this behavior. The gif also illustrates the behavior.
- When not providing a default, the initial value is "None" and then I think it prevents another callback because the components value has the string.
    - Maybe somehow refactoring the initial callback here would fix the issue?
    - Maybe because it's clientside when not providing a default vs. serverside when providing a default?
- Maybe it has to do with this `strictCompareDates` property in material-ui: https://github.com/mui-org/material-ui-pickers/commit/517c5b36d4f88457f6cae5ec4f31d47851cf50d6#diff-2d3494900b8990e6625a6325b184efc2ebe37a6cf8ac4e36a1b79ba4dd117ed2R47-R61

## Supporting Media

![Timezone_Bug](https://user-images.githubusercontent.com/29968158/124128822-c142a880-da42-11eb-8a65-d8dc84c7f0d4.gif)

## To Reproduce
``` python
import dash
import dash_html_components as html
import sd_material_ui as mat
from dash.dependencies import Input, Output


app = dash.Dash()

server = app.server

app.layout = html.Div(
    children=[
        mat.Picker(
            id="default-picker",
            label="default picker",
            type="date",
        ),
        mat.Picker(
            id="string-picker",
            label="string picker",
            type='date',
            value="2020-01-01"
        ),
        html.H6(id="default-value"),
        html.H6(id="string-value"),
    ]
)


@app.callback(
    Output("default-value", "children"),
    Input("default-picker", "value")
)
def update_default(value):
    if value is None:
        return "default-value: None"
    else:
        return "default-value: " + value


@app.callback(
    Output("string-value", "children"),
    Input("string-picker", "value")
)
def update_string(value):
    return "string-value: " + value


if __name__ == "__main__":
    app.run_server(debug=True,
                   use_reloader=False,
                   dev_tools_prune_errors=False)
```

**Comment by coralvanda** [comment]
Good find, @MCBoarder289. Thank you for making this issue, and for including these helpful details! I'll see what I can do about it.

**Comment by MCBoarder289** [comment]
Thanks @coralvanda! Appreciate the quick response on this. Let me know if I can help any further as you're looking into potential solutions.

Also noticed another weird behavior on this same sample app. If you delete all of the text from the component, it will automatically fill in a "1969-12-31", which is suspiciously the start of the epoch. Makes it hard to re-enter text (ex: changing the year).

Would you rather a log another issue for that specific behavior?

**Comment by coralvanda** [comment]
That's ok, we can use this issue for both of those things. Thanks.
