### ISSUE TITLE
Error: sd_material_ui was not found

### ISSUE THREAD

**Issue by wargx** [StratoDem/sd-material-ui#832]
Awesome package, thank you very much for creating it!

But running usage example from README.md gives blank page.

Browser console shows error:
Failed to load resource: the server responded with a status of 404 ()
on https://unpkg.com/sd_material_ui@4.6.0/sd_material_ui/sd_material_ui.min.js resource

And response is "Cannot find package sd_material_ui@4.6.0" when accessing link directly.
Also tried other versions and no version, aka latest, with the same result.

Can you please check what is going on as I really want to use it in my project.

**Comment by coralvanda** [comment]
Thanks, @wargx, pointing this out. I just updated the code in the README example to correct an error there. It runs correctly now. You can check out the `usage.py` file for more examples of components. Please let us know if you run into any other issues. Closing this issue as resolved.
