### ISSUE TITLE
How can i sd_material_ui.Dialog's width

### ISSUE THREAD

**Issue by sylvoslee** [StratoDem/sd-material-ui#84]
How can i sd_material_ui.Dialog's width？
I tried adding style={'width':'300'}，but it didn't work，look forward to your help

`sd_material_ui.Dialog(
        html.Div(children=[
            html.P('Non-modal dialog'),
        ],style={'width':'300'},
                 className="container"),
        id='non-modal-output',
        modal=False,
        open=False)`

**Comment by coralvanda** [comment]
Right now, the `Dialog` component does not accept a `style` prop, so the only way to change its width would be using CSS to pick out the correct `div` and give that the `width` you want.

**Comment by mjclawar** [comment]
With the new `className` props added to the `Dialog` component in [v3.1.2](https://github.com/StratoDem/sd-material-ui/releases/tag/v3.1.2), you should have greater control over styling:
https://github.com/StratoDem/sd-material-ui/blob/master/src/lib/components/Dialog.react.js#L35-L47
