### ISSUE TITLE
Snackbar "open" not resetting to False

### ISSUE THREAD

**Issue by kw3179** [StratoDem/sd-material-ui#92]
Hi!

I have a snackbar in my project, with a callback that tells it to open by setting the snackbar's "open" to True. Once autoHideDuration is triggered, "open" should be reset to False - however, it is staying True and the snackbar opens on every change to the page after that (there are other dropdowns on the page that have nothing to do with the snackbar that trigger it to pop up again).

```
...
materialui.Snackbar(id='snackbar', open=False, message='Alerts updated', autoHideDuration=3000)
... 

@app.callback(
    dash.dependencies.Output('snackbar', 'open'),
    [dash.dependencies.Input('modal', 'cancel_n_clicks_timestamp'),
    dash.dependencies.Input('modal', 'submit_n_clicks_timestamp')])
def handle_snackbar(cancel_n_clicks_timestamp = 0, submit_n_clicks_timestamp = 0):
    if submit_n_clicks_timestamp is None:
        submit_n_clicks_timestamp = 0
    if cancel_n_clicks_timestamp is None:
        cancel_n_clicks_timestamp = 0
    time_now = calendar.timegm(time.gmtime())
    t_submit = int(submit_n_clicks_timestamp)/1000
    t_cancel= int(cancel_n_clicks_timestamp)/1000
    if abs(t_cancel - time_now) < 1:
        return False
    elif abs(t_submit - time_now) < 1:
        return True
    else:
        return False
```

**Comment by coralvanda** [comment]
Sorry to hear that it's giving you trouble, @kw3179 . Would you please share here a complete example of code that has this problem? You've given a lot, but not all of the IDs and other components are present. If I can verify your problem, I'll have a good starting point in trying to fix it.

**Comment by kw3179** [comment]
Hi there, @coralvanda! Sorry I didn't provide enough of my code - here's some more:

``` 
html.Div([
        dcc.ConfirmDialogProvider(children=html.Button('Update My Alerts'),
        id='modal',
        message='Are you sure you want to update?'
        ),
        html.Div(id='output-provider', style={'display': 'none'})
    ], style={'padding': '36px 0px 0px 18px'}),

    materialui.Snackbar(id='snackbar', open=False, message='Alerts updated', autoHideDuration=3000)

    ])
```

```
@app.callback(
    dash.dependencies.Output('snackbar', 'open'),
    [dash.dependencies.Input('modal', 'cancel_n_clicks_timestamp'),
    dash.dependencies.Input('modal', 'submit_n_clicks_timestamp')])
def handle_snackbar(cancel_n_clicks_timestamp = 0, submit_n_clicks_timestamp = 0):
    if submit_n_clicks_timestamp is None:
        submit_n_clicks_timestamp = 0
    if cancel_n_clicks_timestamp is None:
        cancel_n_clicks_timestamp = 0
    time_now = calendar.timegm(time.gmtime())
    t_submit = int(submit_n_clicks_timestamp)/1000
    t_cancel= int(cancel_n_clicks_timestamp)/1000
    if abs(t_cancel - time_now) < 1:
        return False
    elif abs(t_submit - time_now) < 1:
        return True
    else:
        return False
```

`modal` is a ConfirmDialogProvider that pops up when its child button is pressed. I expected that with the callback, when "submit" is clicked it should open the snackbar (which it does), but after that the snackbar should not open any more. But, it's popping up on every change we make, even to things like this that aren't connected to it in any way:

```
    html.Div(children=[
        html.Label('Sensitivity', style={'color': '#666666'}),
        dcc.Slider(
            id='sensitivity-slider',
            min=1,
            max=10,
            value=1,
            marks=
            {'1':'1',
             '2':'2',
             '3':'3',
             '4':'4',
             '5':'5',
             '6':'6',
             '7':'7',
             '8':'8',
             '9':'9',
             '10':'10'}
        )
    ], style={'width': '80%', 'padding': '0px 0px 30px 20px'}),
```

which only has this as a callback:

```
@app.callback(
    dash.dependencies.Output('graph-with-slider', 'figure'),
    [dash.dependencies.Input('sensitivity-slider', 'value'),
     dash.dependencies.Input('metric-dropdown', 'value'),
     dash.dependencies.Input('algorithm-dropdown', 'value'),
     dash.dependencies.Input('datasource-dropdown','value')])
def update_figure(sensitivity, metric, algorithm, datasource):
    if algorithm is None and metric is not None:
        return update_graph_no_alg(get_I_data(metric, "NA", algorithm))
    elif metric is None:
        return {'data': []} # Clear graph when no metric specified
    elif algorithm == "I":
        return update_sensitivity_I(get_I_data(metric, "NA", algorithm), sensitivity)
    elif algorithm == "II":
        return update_sensitivity_II(get_II_data(metric, "NA"), sensitivity)
```

(I had to change some function names here for privacy purposes).

After clicking "submit" on the ConfirmDialogProvider `modal`, changes to `sensitivity-slider` (the slider above), `metric-dropdown` (a dropdown menu), `algorithm-dropdown` (a dropdown menu), and `datasource-dropdown` (a dropdown menu), etc. are causing the snackbar to pop up. But if I click the ConfirmDialogProvider's child button again and click 'cancel', the snackbar no longer comes up on changes (which is why I think "open" isn't being reset to 'False'). 

Does that help explain the problem a little more?

Thanks!

**Comment by coralvanda** [comment]
Thanks @kw3179 for sharing that extra code. I was able to create an example of the issue you're describing. I'll see what I can do about it.

**Comment by coralvanda** [comment]
@kw3179 , I have a change you can make to your code that will correct the behavior of the snackbar. Add an `action` to the snackbar, and use the input from that button in your snackbar callback. They should look something like this;

```
sd_material_ui.Snackbar(
    id='snackbar',
    open=False,
    message='Alerts updated',
    action='Close',
    autoHideDuration=3000),
```

```
@app.callback(
    dash.dependencies.Output('snackbar', 'open'),
    [dash.dependencies.Input('modal', 'cancel_n_clicks_timestamp'),
     dash.dependencies.Input('modal', 'submit_n_clicks_timestamp'),
     dash.dependencies.Input('snackbar', 'n_clicks')])
def handle_snackbar(cancel_n_clicks_timestamp, submit_n_clicks_timestamp, snackbar_close_btn):
    if submit_n_clicks_timestamp is None:
        submit_n_clicks_timestamp = 0
    if cancel_n_clicks_timestamp is None:
        cancel_n_clicks_timestamp = 0
    time_now = calendar.timegm(time.gmtime())
    t_submit = int(submit_n_clicks_timestamp)/1000
    t_cancel = int(cancel_n_clicks_timestamp)/1000
    if abs(t_cancel - time_now) < 1:
        return False
    elif abs(t_submit - time_now) < 1:
        return True
    else:
        return False
```
It isn't necessary to use the `snackbar_close_btn` value in the body of the callback, as long as it's one of the inputs and params. The example I made from your code no longer opens the snackbar at incorrect times after these changes. 

I'm still looking at changing the code for `Snackbar` to fix this, but I don't have an estimate for how long this will take yet.
