### ISSUE TITLE
Should really consider getting these added into dash core component library. 

### ISSUE THREAD

**Issue by SterlingButters** [StratoDem/sd-material-ui#94]
What a great Library!

I found this out of luck, shame that it's not advertised more prominently by Plotly (even though I realize you are a different entity). It could use the additional user documentation that comes with the core components (examples and whatnot).

**Comment by coralvanda** [comment]
Thanks!

We're just an independent project, and not really looking to merge with Plotly, but we do understand the benefit of more helpful documentation. We have that on our TODO list, and we'll add more when we can.
