### ISSUE TITLE
Documentation Request: Schedule of Anticipated Component Releases

### ISSUE THREAD

**Issue by SterlingButters** [StratoDem/sd-material-ui#96]
I realize that an exact schedule is likely a bit unrealistic, however, it would be nice to know that the repo is still pushing developments and that it's not dead. I don't think it's dead but that last commit *was* a couple months ago and I want to see progress here more than I want to see it from Plot.ly themselves.

**Comment by coralvanda** [comment]
That's understandable; it has been a while. I'll think about a more regular schedule so we can keep updating it.

**Comment by SterlingButters** [comment]
I'll do my best! I just made a super simple svg icon component however nothing is rendered by supplying the component to the `icon` property of the `FlatButton` however it *is* accepted by the `children` property. I'll clean up the project and share soon

**Comment by SterlingButters** [comment]
@coralvanda Just forked your project and had some questions:

1) Did you use the `boilerplate` as a template?
2) Did you realize you had so many npm vulnerabilities in your env? (> 1000)
3) What scripts do you use to generate your components? Your `package.json` doesn't have any of the component build scripts?

Yours:
```
"scripts": {
    "extract-metadata": "mkdirp lib && react-docgen --pretty -e index.js -o lib/metadata.json src/components && node -e \"const fs = require('fs'); const path = require('path'); const m = JSON.parse(fs.readFileSync('./lib/metadata.json')); const r = {}; Object.keys(m).forEach(k => r[k.split(path.sep).join('/')] = m[k]); fs.writeFileSync('./lib/metadata.json', JSON.stringify(r, '\t', 2));\"",
    "build-dist": "builder run clean-lib && builder run extract-metadata && webpack --config=config/webpack.config.dev.js --display-error-details",
    "build-dist-production": "builder run clean-lib && builder run extract-metadata && webpack -p --config=config/webpack.config.dist.js",
    "copy-lib": "copyfiles -u 1 lib/* sd_material_ui",
    "install-local": "npm run copy-lib && venv/bin/python setup.py install",
    "prepublish": "npm test && npm run build-dist-production && npm run copy-lib",
    "start": "npm run build-dist && npm run copy-lib",
    "test": "jest --verbose",
    "uninstall-local": "pip uninstall sd-material-ui -y"
  },
```

Boilerplate:
```
"scripts": {
    "start": "webpack-serve ./webpack.serve.config.js --open",
    "validate-init": "python _validate_init.py",
    "prepublish": "npm run validate-init",
    "build:js-dev": "webpack --mode development",
    "build:js": "webpack --mode production",
    "build:py": "dash-generate-components ./src/lib/components plaidash",
    "build:py-activated": "(. venv/bin/activate || venv\\scripts\\activate && npm run build:py)",
    "build:all": "npm run build:js && npm run build:js-dev && npm run build:py",
    "build:all-activated": "(. venv/bin/activate || venv\\scripts\\activate && npm run build:all)"
  },
```

**Comment by coralvanda** [comment]
We did use the boilerplate as a template, but the one we used is outdated now, which might be a bit confusing. You can use the `npm run build-dist-production` script once you've made the changes you want.

Thank you for the alert about the vulnerabilities. We've been behind on updating packages, so we'll get working on that .
